/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardCycleIdSettingsRouteRouteImport } from './routes/dashboard/$cycleId/settings/route'
import { Route as DashboardCycleIdSettingsIndexRouteImport } from './routes/dashboard/$cycleId/settings/index'
import { Route as DashboardCycleIdOverviewIndexRouteImport } from './routes/dashboard/$cycleId/overview/index'
import { Route as DashboardCycleIdSettingsUsersIndexRouteImport } from './routes/dashboard/$cycleId/settings/users/index'
import { Route as DashboardCycleIdSettingsOfferingsIndexRouteImport } from './routes/dashboard/$cycleId/settings/offerings/index'
import { Route as DashboardCycleIdSettingsEventsIndexRouteImport } from './routes/dashboard/$cycleId/settings/events/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCycleIdSettingsRouteRoute =
  DashboardCycleIdSettingsRouteRouteImport.update({
    id: '/$cycleId/settings',
    path: '/$cycleId/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCycleIdSettingsIndexRoute =
  DashboardCycleIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCycleIdSettingsRouteRoute,
  } as any)
const DashboardCycleIdOverviewIndexRoute =
  DashboardCycleIdOverviewIndexRouteImport.update({
    id: '/$cycleId/overview/',
    path: '/$cycleId/overview/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCycleIdSettingsUsersIndexRoute =
  DashboardCycleIdSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardCycleIdSettingsRouteRoute,
  } as any)
const DashboardCycleIdSettingsOfferingsIndexRoute =
  DashboardCycleIdSettingsOfferingsIndexRouteImport.update({
    id: '/offerings/',
    path: '/offerings/',
    getParentRoute: () => DashboardCycleIdSettingsRouteRoute,
  } as any)
const DashboardCycleIdSettingsEventsIndexRoute =
  DashboardCycleIdSettingsEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => DashboardCycleIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$cycleId/settings': typeof DashboardCycleIdSettingsRouteRouteWithChildren
  '/dashboard/$cycleId/overview/': typeof DashboardCycleIdOverviewIndexRoute
  '/dashboard/$cycleId/settings/': typeof DashboardCycleIdSettingsIndexRoute
  '/dashboard/$cycleId/settings/events/': typeof DashboardCycleIdSettingsEventsIndexRoute
  '/dashboard/$cycleId/settings/offerings/': typeof DashboardCycleIdSettingsOfferingsIndexRoute
  '/dashboard/$cycleId/settings/users/': typeof DashboardCycleIdSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$cycleId/overview': typeof DashboardCycleIdOverviewIndexRoute
  '/dashboard/$cycleId/settings': typeof DashboardCycleIdSettingsIndexRoute
  '/dashboard/$cycleId/settings/events': typeof DashboardCycleIdSettingsEventsIndexRoute
  '/dashboard/$cycleId/settings/offerings': typeof DashboardCycleIdSettingsOfferingsIndexRoute
  '/dashboard/$cycleId/settings/users': typeof DashboardCycleIdSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$cycleId/settings': typeof DashboardCycleIdSettingsRouteRouteWithChildren
  '/dashboard/$cycleId/overview/': typeof DashboardCycleIdOverviewIndexRoute
  '/dashboard/$cycleId/settings/': typeof DashboardCycleIdSettingsIndexRoute
  '/dashboard/$cycleId/settings/events/': typeof DashboardCycleIdSettingsEventsIndexRoute
  '/dashboard/$cycleId/settings/offerings/': typeof DashboardCycleIdSettingsOfferingsIndexRoute
  '/dashboard/$cycleId/settings/users/': typeof DashboardCycleIdSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/dashboard/$cycleId/settings'
    | '/dashboard/$cycleId/overview/'
    | '/dashboard/$cycleId/settings/'
    | '/dashboard/$cycleId/settings/events/'
    | '/dashboard/$cycleId/settings/offerings/'
    | '/dashboard/$cycleId/settings/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/dashboard/$cycleId/overview'
    | '/dashboard/$cycleId/settings'
    | '/dashboard/$cycleId/settings/events'
    | '/dashboard/$cycleId/settings/offerings'
    | '/dashboard/$cycleId/settings/users'
  id:
    | '__root__'
    | '/dashboard'
    | '/dashboard/$cycleId/settings'
    | '/dashboard/$cycleId/overview/'
    | '/dashboard/$cycleId/settings/'
    | '/dashboard/$cycleId/settings/events/'
    | '/dashboard/$cycleId/settings/offerings/'
    | '/dashboard/$cycleId/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$cycleId/settings': {
      id: '/dashboard/$cycleId/settings'
      path: '/$cycleId/settings'
      fullPath: '/dashboard/$cycleId/settings'
      preLoaderRoute: typeof DashboardCycleIdSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$cycleId/settings/': {
      id: '/dashboard/$cycleId/settings/'
      path: '/'
      fullPath: '/dashboard/$cycleId/settings/'
      preLoaderRoute: typeof DashboardCycleIdSettingsIndexRouteImport
      parentRoute: typeof DashboardCycleIdSettingsRouteRoute
    }
    '/dashboard/$cycleId/overview/': {
      id: '/dashboard/$cycleId/overview/'
      path: '/$cycleId/overview'
      fullPath: '/dashboard/$cycleId/overview/'
      preLoaderRoute: typeof DashboardCycleIdOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$cycleId/settings/users/': {
      id: '/dashboard/$cycleId/settings/users/'
      path: '/users'
      fullPath: '/dashboard/$cycleId/settings/users/'
      preLoaderRoute: typeof DashboardCycleIdSettingsUsersIndexRouteImport
      parentRoute: typeof DashboardCycleIdSettingsRouteRoute
    }
    '/dashboard/$cycleId/settings/offerings/': {
      id: '/dashboard/$cycleId/settings/offerings/'
      path: '/offerings'
      fullPath: '/dashboard/$cycleId/settings/offerings/'
      preLoaderRoute: typeof DashboardCycleIdSettingsOfferingsIndexRouteImport
      parentRoute: typeof DashboardCycleIdSettingsRouteRoute
    }
    '/dashboard/$cycleId/settings/events/': {
      id: '/dashboard/$cycleId/settings/events/'
      path: '/events'
      fullPath: '/dashboard/$cycleId/settings/events/'
      preLoaderRoute: typeof DashboardCycleIdSettingsEventsIndexRouteImport
      parentRoute: typeof DashboardCycleIdSettingsRouteRoute
    }
  }
}

interface DashboardCycleIdSettingsRouteRouteChildren {
  DashboardCycleIdSettingsIndexRoute: typeof DashboardCycleIdSettingsIndexRoute
  DashboardCycleIdSettingsEventsIndexRoute: typeof DashboardCycleIdSettingsEventsIndexRoute
  DashboardCycleIdSettingsOfferingsIndexRoute: typeof DashboardCycleIdSettingsOfferingsIndexRoute
  DashboardCycleIdSettingsUsersIndexRoute: typeof DashboardCycleIdSettingsUsersIndexRoute
}

const DashboardCycleIdSettingsRouteRouteChildren: DashboardCycleIdSettingsRouteRouteChildren =
  {
    DashboardCycleIdSettingsIndexRoute: DashboardCycleIdSettingsIndexRoute,
    DashboardCycleIdSettingsEventsIndexRoute:
      DashboardCycleIdSettingsEventsIndexRoute,
    DashboardCycleIdSettingsOfferingsIndexRoute:
      DashboardCycleIdSettingsOfferingsIndexRoute,
    DashboardCycleIdSettingsUsersIndexRoute:
      DashboardCycleIdSettingsUsersIndexRoute,
  }

const DashboardCycleIdSettingsRouteRouteWithChildren =
  DashboardCycleIdSettingsRouteRoute._addFileChildren(
    DashboardCycleIdSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCycleIdSettingsRouteRoute: typeof DashboardCycleIdSettingsRouteRouteWithChildren
  DashboardCycleIdOverviewIndexRoute: typeof DashboardCycleIdOverviewIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCycleIdSettingsRouteRoute:
    DashboardCycleIdSettingsRouteRouteWithChildren,
  DashboardCycleIdOverviewIndexRoute: DashboardCycleIdOverviewIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
