/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardSetupRouteRouteImport } from './routes/dashboard/setup/route'
import { Route as DashboardProtectedRouteRouteImport } from './routes/dashboard/_protected/route'
import { Route as DashboardSetupIndexRouteImport } from './routes/dashboard/setup/index'
import { Route as DashboardProtectedIndexRouteImport } from './routes/dashboard/_protected/index'
import { Route as DashboardProtectedNotificationsRouteRouteImport } from './routes/dashboard/_protected/notifications/route'
import { Route as DashboardProtectedNotificationsIndexRouteImport } from './routes/dashboard/_protected/notifications/index'
import { Route as DashboardProtectedApplicantsIndexRouteImport } from './routes/dashboard/_protected/applicants/index'
import { Route as DashboardProtectedCycleIdSettingsRouteRouteImport } from './routes/dashboard/_protected/$cycleId/settings/route'
import { Route as DashboardProtectedCycleIdDocumentsRouteRouteImport } from './routes/dashboard/_protected/$cycleId/documents/route'
import { Route as DashboardProtectedCycleIdApplicationsRouteRouteImport } from './routes/dashboard/_protected/$cycleId/applications/route'
import { Route as DashboardProtectedNotificationsTemplatesIndexRouteImport } from './routes/dashboard/_protected/notifications/templates/index'
import { Route as DashboardProtectedApplicantsApplicantIdIndexRouteImport } from './routes/dashboard/_protected/applicants/$applicantId/index'
import { Route as DashboardProtectedCycleIdSettingsIndexRouteImport } from './routes/dashboard/_protected/$cycleId/settings/index'
import { Route as DashboardProtectedCycleIdOverviewIndexRouteImport } from './routes/dashboard/_protected/$cycleId/overview/index'
import { Route as DashboardProtectedCycleIdDocumentsIndexRouteImport } from './routes/dashboard/_protected/$cycleId/documents/index'
import { Route as DashboardProtectedCycleIdApplicationsIndexRouteImport } from './routes/dashboard/_protected/$cycleId/applications/index'
import { Route as DashboardProtectedCycleIdSettingsUsersIndexRouteImport } from './routes/dashboard/_protected/$cycleId/settings/users/index'
import { Route as DashboardProtectedCycleIdSettingsOfferingsIndexRouteImport } from './routes/dashboard/_protected/$cycleId/settings/offerings/index'
import { Route as DashboardProtectedCycleIdSettingsEventsIndexRouteImport } from './routes/dashboard/_protected/$cycleId/settings/events/index'
import { Route as DashboardProtectedCycleIdApplicationsApplicationIdIndexRouteImport } from './routes/dashboard/_protected/$cycleId/applications/$applicationId/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSetupRouteRoute = DashboardSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProtectedRouteRoute = DashboardProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupIndexRoute = DashboardSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSetupRouteRoute,
} as any)
const DashboardProtectedIndexRoute = DashboardProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProtectedRouteRoute,
} as any)
const DashboardProtectedNotificationsRouteRoute =
  DashboardProtectedNotificationsRouteRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedNotificationsIndexRoute =
  DashboardProtectedNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedNotificationsRouteRoute,
  } as any)
const DashboardProtectedApplicantsIndexRoute =
  DashboardProtectedApplicantsIndexRouteImport.update({
    id: '/applicants/',
    path: '/applicants/',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedCycleIdSettingsRouteRoute =
  DashboardProtectedCycleIdSettingsRouteRouteImport.update({
    id: '/$cycleId/settings',
    path: '/$cycleId/settings',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedCycleIdDocumentsRouteRoute =
  DashboardProtectedCycleIdDocumentsRouteRouteImport.update({
    id: '/$cycleId/documents',
    path: '/$cycleId/documents',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedCycleIdApplicationsRouteRoute =
  DashboardProtectedCycleIdApplicationsRouteRouteImport.update({
    id: '/$cycleId/applications',
    path: '/$cycleId/applications',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedNotificationsTemplatesIndexRoute =
  DashboardProtectedNotificationsTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => DashboardProtectedNotificationsRouteRoute,
  } as any)
const DashboardProtectedApplicantsApplicantIdIndexRoute =
  DashboardProtectedApplicantsApplicantIdIndexRouteImport.update({
    id: '/applicants/$applicantId/',
    path: '/applicants/$applicantId/',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedCycleIdSettingsIndexRoute =
  DashboardProtectedCycleIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedCycleIdSettingsRouteRoute,
  } as any)
const DashboardProtectedCycleIdOverviewIndexRoute =
  DashboardProtectedCycleIdOverviewIndexRouteImport.update({
    id: '/$cycleId/overview/',
    path: '/$cycleId/overview/',
    getParentRoute: () => DashboardProtectedRouteRoute,
  } as any)
const DashboardProtectedCycleIdDocumentsIndexRoute =
  DashboardProtectedCycleIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedCycleIdDocumentsRouteRoute,
  } as any)
const DashboardProtectedCycleIdApplicationsIndexRoute =
  DashboardProtectedCycleIdApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProtectedCycleIdApplicationsRouteRoute,
  } as any)
const DashboardProtectedCycleIdSettingsUsersIndexRoute =
  DashboardProtectedCycleIdSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardProtectedCycleIdSettingsRouteRoute,
  } as any)
const DashboardProtectedCycleIdSettingsOfferingsIndexRoute =
  DashboardProtectedCycleIdSettingsOfferingsIndexRouteImport.update({
    id: '/offerings/',
    path: '/offerings/',
    getParentRoute: () => DashboardProtectedCycleIdSettingsRouteRoute,
  } as any)
const DashboardProtectedCycleIdSettingsEventsIndexRoute =
  DashboardProtectedCycleIdSettingsEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => DashboardProtectedCycleIdSettingsRouteRoute,
  } as any)
const DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute =
  DashboardProtectedCycleIdApplicationsApplicationIdIndexRouteImport.update({
    id: '/$applicationId/',
    path: '/$applicationId/',
    getParentRoute: () => DashboardProtectedCycleIdApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardProtectedRouteRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRouteRouteWithChildren
  '/dashboard/notifications': typeof DashboardProtectedNotificationsRouteRouteWithChildren
  '/dashboard/': typeof DashboardProtectedIndexRoute
  '/dashboard/setup/': typeof DashboardSetupIndexRoute
  '/dashboard/$cycleId/applications': typeof DashboardProtectedCycleIdApplicationsRouteRouteWithChildren
  '/dashboard/$cycleId/documents': typeof DashboardProtectedCycleIdDocumentsRouteRouteWithChildren
  '/dashboard/$cycleId/settings': typeof DashboardProtectedCycleIdSettingsRouteRouteWithChildren
  '/dashboard/applicants/': typeof DashboardProtectedApplicantsIndexRoute
  '/dashboard/notifications/': typeof DashboardProtectedNotificationsIndexRoute
  '/dashboard/$cycleId/applications/': typeof DashboardProtectedCycleIdApplicationsIndexRoute
  '/dashboard/$cycleId/documents/': typeof DashboardProtectedCycleIdDocumentsIndexRoute
  '/dashboard/$cycleId/overview/': typeof DashboardProtectedCycleIdOverviewIndexRoute
  '/dashboard/$cycleId/settings/': typeof DashboardProtectedCycleIdSettingsIndexRoute
  '/dashboard/applicants/$applicantId/': typeof DashboardProtectedApplicantsApplicantIdIndexRoute
  '/dashboard/notifications/templates/': typeof DashboardProtectedNotificationsTemplatesIndexRoute
  '/dashboard/$cycleId/applications/$applicationId/': typeof DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute
  '/dashboard/$cycleId/settings/events/': typeof DashboardProtectedCycleIdSettingsEventsIndexRoute
  '/dashboard/$cycleId/settings/offerings/': typeof DashboardProtectedCycleIdSettingsOfferingsIndexRoute
  '/dashboard/$cycleId/settings/users/': typeof DashboardProtectedCycleIdSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardProtectedIndexRoute
  '/dashboard/setup': typeof DashboardSetupIndexRoute
  '/dashboard/applicants': typeof DashboardProtectedApplicantsIndexRoute
  '/dashboard/notifications': typeof DashboardProtectedNotificationsIndexRoute
  '/dashboard/$cycleId/applications': typeof DashboardProtectedCycleIdApplicationsIndexRoute
  '/dashboard/$cycleId/documents': typeof DashboardProtectedCycleIdDocumentsIndexRoute
  '/dashboard/$cycleId/overview': typeof DashboardProtectedCycleIdOverviewIndexRoute
  '/dashboard/$cycleId/settings': typeof DashboardProtectedCycleIdSettingsIndexRoute
  '/dashboard/applicants/$applicantId': typeof DashboardProtectedApplicantsApplicantIdIndexRoute
  '/dashboard/notifications/templates': typeof DashboardProtectedNotificationsTemplatesIndexRoute
  '/dashboard/$cycleId/applications/$applicationId': typeof DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute
  '/dashboard/$cycleId/settings/events': typeof DashboardProtectedCycleIdSettingsEventsIndexRoute
  '/dashboard/$cycleId/settings/offerings': typeof DashboardProtectedCycleIdSettingsOfferingsIndexRoute
  '/dashboard/$cycleId/settings/users': typeof DashboardProtectedCycleIdSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/_protected': typeof DashboardProtectedRouteRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRouteRouteWithChildren
  '/dashboard/_protected/notifications': typeof DashboardProtectedNotificationsRouteRouteWithChildren
  '/dashboard/_protected/': typeof DashboardProtectedIndexRoute
  '/dashboard/setup/': typeof DashboardSetupIndexRoute
  '/dashboard/_protected/$cycleId/applications': typeof DashboardProtectedCycleIdApplicationsRouteRouteWithChildren
  '/dashboard/_protected/$cycleId/documents': typeof DashboardProtectedCycleIdDocumentsRouteRouteWithChildren
  '/dashboard/_protected/$cycleId/settings': typeof DashboardProtectedCycleIdSettingsRouteRouteWithChildren
  '/dashboard/_protected/applicants/': typeof DashboardProtectedApplicantsIndexRoute
  '/dashboard/_protected/notifications/': typeof DashboardProtectedNotificationsIndexRoute
  '/dashboard/_protected/$cycleId/applications/': typeof DashboardProtectedCycleIdApplicationsIndexRoute
  '/dashboard/_protected/$cycleId/documents/': typeof DashboardProtectedCycleIdDocumentsIndexRoute
  '/dashboard/_protected/$cycleId/overview/': typeof DashboardProtectedCycleIdOverviewIndexRoute
  '/dashboard/_protected/$cycleId/settings/': typeof DashboardProtectedCycleIdSettingsIndexRoute
  '/dashboard/_protected/applicants/$applicantId/': typeof DashboardProtectedApplicantsApplicantIdIndexRoute
  '/dashboard/_protected/notifications/templates/': typeof DashboardProtectedNotificationsTemplatesIndexRoute
  '/dashboard/_protected/$cycleId/applications/$applicationId/': typeof DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute
  '/dashboard/_protected/$cycleId/settings/events/': typeof DashboardProtectedCycleIdSettingsEventsIndexRoute
  '/dashboard/_protected/$cycleId/settings/offerings/': typeof DashboardProtectedCycleIdSettingsOfferingsIndexRoute
  '/dashboard/_protected/$cycleId/settings/users/': typeof DashboardProtectedCycleIdSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/dashboard/setup'
    | '/dashboard/notifications'
    | '/dashboard/'
    | '/dashboard/setup/'
    | '/dashboard/$cycleId/applications'
    | '/dashboard/$cycleId/documents'
    | '/dashboard/$cycleId/settings'
    | '/dashboard/applicants/'
    | '/dashboard/notifications/'
    | '/dashboard/$cycleId/applications/'
    | '/dashboard/$cycleId/documents/'
    | '/dashboard/$cycleId/overview/'
    | '/dashboard/$cycleId/settings/'
    | '/dashboard/applicants/$applicantId/'
    | '/dashboard/notifications/templates/'
    | '/dashboard/$cycleId/applications/$applicationId/'
    | '/dashboard/$cycleId/settings/events/'
    | '/dashboard/$cycleId/settings/offerings/'
    | '/dashboard/$cycleId/settings/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/dashboard/setup'
    | '/dashboard/applicants'
    | '/dashboard/notifications'
    | '/dashboard/$cycleId/applications'
    | '/dashboard/$cycleId/documents'
    | '/dashboard/$cycleId/overview'
    | '/dashboard/$cycleId/settings'
    | '/dashboard/applicants/$applicantId'
    | '/dashboard/notifications/templates'
    | '/dashboard/$cycleId/applications/$applicationId'
    | '/dashboard/$cycleId/settings/events'
    | '/dashboard/$cycleId/settings/offerings'
    | '/dashboard/$cycleId/settings/users'
  id:
    | '__root__'
    | '/dashboard'
    | '/dashboard/_protected'
    | '/dashboard/setup'
    | '/dashboard/_protected/notifications'
    | '/dashboard/_protected/'
    | '/dashboard/setup/'
    | '/dashboard/_protected/$cycleId/applications'
    | '/dashboard/_protected/$cycleId/documents'
    | '/dashboard/_protected/$cycleId/settings'
    | '/dashboard/_protected/applicants/'
    | '/dashboard/_protected/notifications/'
    | '/dashboard/_protected/$cycleId/applications/'
    | '/dashboard/_protected/$cycleId/documents/'
    | '/dashboard/_protected/$cycleId/overview/'
    | '/dashboard/_protected/$cycleId/settings/'
    | '/dashboard/_protected/applicants/$applicantId/'
    | '/dashboard/_protected/notifications/templates/'
    | '/dashboard/_protected/$cycleId/applications/$applicationId/'
    | '/dashboard/_protected/$cycleId/settings/events/'
    | '/dashboard/_protected/$cycleId/settings/offerings/'
    | '/dashboard/_protected/$cycleId/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/_protected': {
      id: '/dashboard/_protected'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardProtectedRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setup/': {
      id: '/dashboard/setup/'
      path: '/'
      fullPath: '/dashboard/setup/'
      preLoaderRoute: typeof DashboardSetupIndexRouteImport
      parentRoute: typeof DashboardSetupRouteRoute
    }
    '/dashboard/_protected/': {
      id: '/dashboard/_protected/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardProtectedIndexRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/notifications': {
      id: '/dashboard/_protected/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardProtectedNotificationsRouteRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/notifications/': {
      id: '/dashboard/_protected/notifications/'
      path: '/'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof DashboardProtectedNotificationsIndexRouteImport
      parentRoute: typeof DashboardProtectedNotificationsRouteRoute
    }
    '/dashboard/_protected/applicants/': {
      id: '/dashboard/_protected/applicants/'
      path: '/applicants'
      fullPath: '/dashboard/applicants/'
      preLoaderRoute: typeof DashboardProtectedApplicantsIndexRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/$cycleId/settings': {
      id: '/dashboard/_protected/$cycleId/settings'
      path: '/$cycleId/settings'
      fullPath: '/dashboard/$cycleId/settings'
      preLoaderRoute: typeof DashboardProtectedCycleIdSettingsRouteRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/$cycleId/documents': {
      id: '/dashboard/_protected/$cycleId/documents'
      path: '/$cycleId/documents'
      fullPath: '/dashboard/$cycleId/documents'
      preLoaderRoute: typeof DashboardProtectedCycleIdDocumentsRouteRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/$cycleId/applications': {
      id: '/dashboard/_protected/$cycleId/applications'
      path: '/$cycleId/applications'
      fullPath: '/dashboard/$cycleId/applications'
      preLoaderRoute: typeof DashboardProtectedCycleIdApplicationsRouteRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/notifications/templates/': {
      id: '/dashboard/_protected/notifications/templates/'
      path: '/templates'
      fullPath: '/dashboard/notifications/templates/'
      preLoaderRoute: typeof DashboardProtectedNotificationsTemplatesIndexRouteImport
      parentRoute: typeof DashboardProtectedNotificationsRouteRoute
    }
    '/dashboard/_protected/applicants/$applicantId/': {
      id: '/dashboard/_protected/applicants/$applicantId/'
      path: '/applicants/$applicantId'
      fullPath: '/dashboard/applicants/$applicantId/'
      preLoaderRoute: typeof DashboardProtectedApplicantsApplicantIdIndexRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/$cycleId/settings/': {
      id: '/dashboard/_protected/$cycleId/settings/'
      path: '/'
      fullPath: '/dashboard/$cycleId/settings/'
      preLoaderRoute: typeof DashboardProtectedCycleIdSettingsIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdSettingsRouteRoute
    }
    '/dashboard/_protected/$cycleId/overview/': {
      id: '/dashboard/_protected/$cycleId/overview/'
      path: '/$cycleId/overview'
      fullPath: '/dashboard/$cycleId/overview/'
      preLoaderRoute: typeof DashboardProtectedCycleIdOverviewIndexRouteImport
      parentRoute: typeof DashboardProtectedRouteRoute
    }
    '/dashboard/_protected/$cycleId/documents/': {
      id: '/dashboard/_protected/$cycleId/documents/'
      path: '/'
      fullPath: '/dashboard/$cycleId/documents/'
      preLoaderRoute: typeof DashboardProtectedCycleIdDocumentsIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdDocumentsRouteRoute
    }
    '/dashboard/_protected/$cycleId/applications/': {
      id: '/dashboard/_protected/$cycleId/applications/'
      path: '/'
      fullPath: '/dashboard/$cycleId/applications/'
      preLoaderRoute: typeof DashboardProtectedCycleIdApplicationsIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdApplicationsRouteRoute
    }
    '/dashboard/_protected/$cycleId/settings/users/': {
      id: '/dashboard/_protected/$cycleId/settings/users/'
      path: '/users'
      fullPath: '/dashboard/$cycleId/settings/users/'
      preLoaderRoute: typeof DashboardProtectedCycleIdSettingsUsersIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdSettingsRouteRoute
    }
    '/dashboard/_protected/$cycleId/settings/offerings/': {
      id: '/dashboard/_protected/$cycleId/settings/offerings/'
      path: '/offerings'
      fullPath: '/dashboard/$cycleId/settings/offerings/'
      preLoaderRoute: typeof DashboardProtectedCycleIdSettingsOfferingsIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdSettingsRouteRoute
    }
    '/dashboard/_protected/$cycleId/settings/events/': {
      id: '/dashboard/_protected/$cycleId/settings/events/'
      path: '/events'
      fullPath: '/dashboard/$cycleId/settings/events/'
      preLoaderRoute: typeof DashboardProtectedCycleIdSettingsEventsIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdSettingsRouteRoute
    }
    '/dashboard/_protected/$cycleId/applications/$applicationId/': {
      id: '/dashboard/_protected/$cycleId/applications/$applicationId/'
      path: '/$applicationId'
      fullPath: '/dashboard/$cycleId/applications/$applicationId/'
      preLoaderRoute: typeof DashboardProtectedCycleIdApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof DashboardProtectedCycleIdApplicationsRouteRoute
    }
  }
}

interface DashboardProtectedNotificationsRouteRouteChildren {
  DashboardProtectedNotificationsIndexRoute: typeof DashboardProtectedNotificationsIndexRoute
  DashboardProtectedNotificationsTemplatesIndexRoute: typeof DashboardProtectedNotificationsTemplatesIndexRoute
}

const DashboardProtectedNotificationsRouteRouteChildren: DashboardProtectedNotificationsRouteRouteChildren =
  {
    DashboardProtectedNotificationsIndexRoute:
      DashboardProtectedNotificationsIndexRoute,
    DashboardProtectedNotificationsTemplatesIndexRoute:
      DashboardProtectedNotificationsTemplatesIndexRoute,
  }

const DashboardProtectedNotificationsRouteRouteWithChildren =
  DashboardProtectedNotificationsRouteRoute._addFileChildren(
    DashboardProtectedNotificationsRouteRouteChildren,
  )

interface DashboardProtectedCycleIdApplicationsRouteRouteChildren {
  DashboardProtectedCycleIdApplicationsIndexRoute: typeof DashboardProtectedCycleIdApplicationsIndexRoute
  DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute: typeof DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute
}

const DashboardProtectedCycleIdApplicationsRouteRouteChildren: DashboardProtectedCycleIdApplicationsRouteRouteChildren =
  {
    DashboardProtectedCycleIdApplicationsIndexRoute:
      DashboardProtectedCycleIdApplicationsIndexRoute,
    DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute:
      DashboardProtectedCycleIdApplicationsApplicationIdIndexRoute,
  }

const DashboardProtectedCycleIdApplicationsRouteRouteWithChildren =
  DashboardProtectedCycleIdApplicationsRouteRoute._addFileChildren(
    DashboardProtectedCycleIdApplicationsRouteRouteChildren,
  )

interface DashboardProtectedCycleIdDocumentsRouteRouteChildren {
  DashboardProtectedCycleIdDocumentsIndexRoute: typeof DashboardProtectedCycleIdDocumentsIndexRoute
}

const DashboardProtectedCycleIdDocumentsRouteRouteChildren: DashboardProtectedCycleIdDocumentsRouteRouteChildren =
  {
    DashboardProtectedCycleIdDocumentsIndexRoute:
      DashboardProtectedCycleIdDocumentsIndexRoute,
  }

const DashboardProtectedCycleIdDocumentsRouteRouteWithChildren =
  DashboardProtectedCycleIdDocumentsRouteRoute._addFileChildren(
    DashboardProtectedCycleIdDocumentsRouteRouteChildren,
  )

interface DashboardProtectedCycleIdSettingsRouteRouteChildren {
  DashboardProtectedCycleIdSettingsIndexRoute: typeof DashboardProtectedCycleIdSettingsIndexRoute
  DashboardProtectedCycleIdSettingsEventsIndexRoute: typeof DashboardProtectedCycleIdSettingsEventsIndexRoute
  DashboardProtectedCycleIdSettingsOfferingsIndexRoute: typeof DashboardProtectedCycleIdSettingsOfferingsIndexRoute
  DashboardProtectedCycleIdSettingsUsersIndexRoute: typeof DashboardProtectedCycleIdSettingsUsersIndexRoute
}

const DashboardProtectedCycleIdSettingsRouteRouteChildren: DashboardProtectedCycleIdSettingsRouteRouteChildren =
  {
    DashboardProtectedCycleIdSettingsIndexRoute:
      DashboardProtectedCycleIdSettingsIndexRoute,
    DashboardProtectedCycleIdSettingsEventsIndexRoute:
      DashboardProtectedCycleIdSettingsEventsIndexRoute,
    DashboardProtectedCycleIdSettingsOfferingsIndexRoute:
      DashboardProtectedCycleIdSettingsOfferingsIndexRoute,
    DashboardProtectedCycleIdSettingsUsersIndexRoute:
      DashboardProtectedCycleIdSettingsUsersIndexRoute,
  }

const DashboardProtectedCycleIdSettingsRouteRouteWithChildren =
  DashboardProtectedCycleIdSettingsRouteRoute._addFileChildren(
    DashboardProtectedCycleIdSettingsRouteRouteChildren,
  )

interface DashboardProtectedRouteRouteChildren {
  DashboardProtectedNotificationsRouteRoute: typeof DashboardProtectedNotificationsRouteRouteWithChildren
  DashboardProtectedIndexRoute: typeof DashboardProtectedIndexRoute
  DashboardProtectedCycleIdApplicationsRouteRoute: typeof DashboardProtectedCycleIdApplicationsRouteRouteWithChildren
  DashboardProtectedCycleIdDocumentsRouteRoute: typeof DashboardProtectedCycleIdDocumentsRouteRouteWithChildren
  DashboardProtectedCycleIdSettingsRouteRoute: typeof DashboardProtectedCycleIdSettingsRouteRouteWithChildren
  DashboardProtectedApplicantsIndexRoute: typeof DashboardProtectedApplicantsIndexRoute
  DashboardProtectedCycleIdOverviewIndexRoute: typeof DashboardProtectedCycleIdOverviewIndexRoute
  DashboardProtectedApplicantsApplicantIdIndexRoute: typeof DashboardProtectedApplicantsApplicantIdIndexRoute
}

const DashboardProtectedRouteRouteChildren: DashboardProtectedRouteRouteChildren =
  {
    DashboardProtectedNotificationsRouteRoute:
      DashboardProtectedNotificationsRouteRouteWithChildren,
    DashboardProtectedIndexRoute: DashboardProtectedIndexRoute,
    DashboardProtectedCycleIdApplicationsRouteRoute:
      DashboardProtectedCycleIdApplicationsRouteRouteWithChildren,
    DashboardProtectedCycleIdDocumentsRouteRoute:
      DashboardProtectedCycleIdDocumentsRouteRouteWithChildren,
    DashboardProtectedCycleIdSettingsRouteRoute:
      DashboardProtectedCycleIdSettingsRouteRouteWithChildren,
    DashboardProtectedApplicantsIndexRoute:
      DashboardProtectedApplicantsIndexRoute,
    DashboardProtectedCycleIdOverviewIndexRoute:
      DashboardProtectedCycleIdOverviewIndexRoute,
    DashboardProtectedApplicantsApplicantIdIndexRoute:
      DashboardProtectedApplicantsApplicantIdIndexRoute,
  }

const DashboardProtectedRouteRouteWithChildren =
  DashboardProtectedRouteRoute._addFileChildren(
    DashboardProtectedRouteRouteChildren,
  )

interface DashboardSetupRouteRouteChildren {
  DashboardSetupIndexRoute: typeof DashboardSetupIndexRoute
}

const DashboardSetupRouteRouteChildren: DashboardSetupRouteRouteChildren = {
  DashboardSetupIndexRoute: DashboardSetupIndexRoute,
}

const DashboardSetupRouteRouteWithChildren =
  DashboardSetupRouteRoute._addFileChildren(DashboardSetupRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardProtectedRouteRoute: typeof DashboardProtectedRouteRouteWithChildren
  DashboardSetupRouteRoute: typeof DashboardSetupRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProtectedRouteRoute: DashboardProtectedRouteRouteWithChildren,
  DashboardSetupRouteRoute: DashboardSetupRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
